const errorsEnums = {
  BAD_REQUEST: 1,
  VALIDATION_ERROR: 2,
  AUTH_ERROR: 3,
  RESOURCE_NOT_FOUND: 4,
  DATABASE_ERROR: 5,
  INTERNAL_SERVER_ERROR: 6,
  CONFLICT_ERROR: 7,
  PERMISSION_ERROR: 8,
  INVALID_TYPES_ERROR: 9,
  ROUTING_ERROR: 10,
};

export default errorsEnums;
